import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";
import client from "../src/context/apollo-client";
import { useEffect } from "react";
import axios from "axios";

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query UserById {
        userById(_id: "61d6d8115b57b352862be29e") {
          username
        }
      }
    `,
  });

  return {
    props: {
      user: data,
    },
  };
}

export default function Home() {
  const getUser = async () => {
    const res = await fetch("/api/get-user", {
      method: "GET",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
    });
    const resData = await res.json();
    console.log(resData);
  };

  const createUser = async () => {
    const res = await axios.post("/api/create-user", {
      username: "test",
      password: "1234",
      name: "test",
    });
    const resData = res;
    console.log(resData);
  };

  const login = async () => {
    const res = await axios.post("/api/login", {
      username: "test",
      password: "1234",
    });
    const resData = res.data;
    console.log(resData);
  };

  useEffect(() => {
    getUser();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => createUser()}>click here</button>
      <button onClick={() => login()}>login here</button>
    </div>
  );
}
